feat: :art: add functions yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -48,6 +48,28 @@ jobs:
           echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
+      - name: Update system and install Docker if not present
+        run: |
+          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+          # Update the system
+          sudo yum update -y
+
+          # Check if Docker is installed
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found, installing..."
+            sudo yum install docker -y
+            sudo service docker start
+            sudo systemctl enable docker
+            sudo usermod -aG docker ec2-user
+          else
+            echo "Docker is already installed."
+          fi
+
+          # Ensure Docker is running
+          sudo service docker start
+          EOF
+
       - name: Deploy to EC2
         run: |
           ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
